### Flight Price Prediction

In [1]:
from idlelib.search import find_again

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
train_df = pd.read_excel('Data_Train.xlsx')
train_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [4]:
test_df = pd.read_excel('Test_set.xlsx')
test_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info
0,Jet Airways,6/06/2019,Delhi,Cochin,DEL → BOM → COK,17:30,04:25 07 Jun,10h 55m,1 stop,No info
1,IndiGo,12/05/2019,Kolkata,Banglore,CCU → MAA → BLR,06:20,10:20,4h,1 stop,No info
2,Jet Airways,21/05/2019,Delhi,Cochin,DEL → BOM → COK,19:15,19:00 22 May,23h 45m,1 stop,In-flight meal not included
3,Multiple carriers,21/05/2019,Delhi,Cochin,DEL → BOM → COK,08:00,21:00,13h,1 stop,No info
4,Air Asia,24/06/2019,Banglore,Delhi,BLR → DEL,23:55,02:45 25 Jun,2h 50m,non-stop,No info

In [5]:
final_df = pd.concat([train_df, test_df], ignore_index=True)
final_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0

In [6]:
final_df.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
13349,Air India,6/06/2019,Kolkata,Banglore,CCU → DEL → BLR,20:30,20:25 07 Jun,23h 55m,1 stop,No info,NaN
13350,IndiGo,27/03/2019,Kolkata,Banglore,CCU → BLR,14:20,16:55,2h 35m,non-stop,No info,NaN
13351,Jet Airways,6/03/2019,Delhi,Cochin,DEL → BOM → COK,21:50,04:25 07 Mar,6h 35m,1 stop,No info,NaN
13352,Air India,6/03/2019,Delhi,Cochin,DEL → BOM → COK,04:00,19:15,15h 15m,1 stop,No info,NaN
13353,Multiple carriers,15/06/2019,Delhi,Cochin,DEL → BOM → COK,04:55,19:15,14h 20m,1 stop,No info,NaN

In [8]:
final_df['Date'] = final_df['Date_of_Journey'].str.split('/').str[0]
final_df['Month'] = final_df['Date_of_Journey'].str.split('/').str[1]
final_df['Year'] = final_df['Date_of_Journey'].str.split('/').str[2]

In [9]:
final_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,05,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0,9,06,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,05,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,01,03,2019

In [10]:
final_df['Date'] = final_df['Date'].astype(int)
final_df['Month'] = final_df['Month'].astype(int)
final_df['Year'] = final_df['Year'].astype(int)

In [11]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Date_of_Journey  13354 non-null  object
 2   Source           13354 non-null  object
 3   Destination      13354 non-null  object
 4   Route            13353 non-null  object
 5   Dep_Time         13354 non-null  object
 6   Arrival_Time     13354 non-null  object
 7   Duration         13354 non-null  object
 8   Total_Stops      13353 non-null  object
 9   Additional_Info  13354 non-null  object
 10  Price            10683 non-null  float64
 11  Date             13354 non-null  int64
 12  Month            13354 non-null  int64
 13  Year             13354 non-null  int64
dtypes: float64(1), int64(3), object(10)
memory usage: 1.4+ MB

In [12]:
final_df.drop('Date_of_Journey', axis=1, inplace=True)

In [14]:
final_df.head(10)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,3,2019
5,SpiceJet,Kolkata,Banglore,CCU → BLR,09:00,11:25,2h 25m,non-stop,No info,3873.0,24,6,2019
6,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,18:55,10:25 13 Mar,15h 30m,1 stop,In-flight meal not included,11087.0,12,3,2019
7,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,08:00,05:05 02 Mar,21h 5m,1 stop,No info,22270.0,1,3,2019
8,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,08:55,10:25 13 Mar,25h 30m,1 stop,In-flight meal not included,11087.0,12,3,2019
9,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,11:25,19:15,7h 50m,1 stop,No info,8625.0,27,5,2019

In [16]:
final_df['Arrival_Time'] = final_df['Arrival_Time'].str.split(' ').str[0]

In [17]:
final_df.head(10)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897.0,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882.0,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,3,2019
5,SpiceJet,Kolkata,Banglore,CCU → BLR,09:00,11:25,2h 25m,non-stop,No info,3873.0,24,6,2019
6,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,18:55,10:25,15h 30m,1 stop,In-flight meal not included,11087.0,12,3,2019
7,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,08:00,05:05,21h 5m,1 stop,No info,22270.0,1,3,2019
8,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,08:55,10:25,25h 30m,1 stop,In-flight meal not included,11087.0,12,3,2019
9,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,11:25,19:15,7h 50m,1 stop,No info,8625.0,27,5,2019

In [20]:
final_df['Arrival_Hour'] = final_df['Arrival_Time'].str.split(':').str[0]
final_df['Arrival_Min'] = final_df['Arrival_Time'].str.split(':').str[1]
final_df.head(10)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897.0,24,3,2019,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882.0,9,6,2019,04,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,3,2019,21,35
5,SpiceJet,Kolkata,Banglore,CCU → BLR,09:00,11:25,2h 25m,non-stop,No info,3873.0,24,6,2019,11,25
6,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,18:55,10:25,15h 30m,1 stop,In-flight meal not included,11087.0,12,3,2019,10,25
7,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,08:00,05:05,21h 5m,1 stop,No info,22270.0,1,3,2019,05,05
8,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,08:55,10:25,25h 30m,1 stop,In-flight meal not included,11087.0,12,3,2019,10,25
9,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,11:25,19:15,7h 50m,1 stop,No info,8625.0,27,5,2019,19,15

In [21]:
final_df['Arrival_Hour'] = final_df['Arrival_Hour'].astype(int)
final_df['Arrival_Min'] = final_df['Arrival_Min'].astype(int)

In [22]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Dep_Time         13354 non-null  object
 5   Arrival_Time     13354 non-null  object
 6   Duration         13354 non-null  object
 7   Total_Stops      13353 non-null  object
 8   Additional_Info  13354 non-null  object
 9   Price            10683 non-null  float64
 10  Date             13354 non-null  int64
 11  Month            13354 non-null  int64
 12  Year             13354 non-null  int64
 13  Arrival_Hour     13354 non-null  int64
 14  Arrival_Min      13354 non-null  int64
dtypes: float64(1), int64(5), object(9)
memory usage: 1.5+ MB

In [23]:
final_df.drop('Arrival_Time', axis=1, inplace=True)

In [24]:
final_df.head(10)

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882.0,9,6,2019,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1 stop,No info,6218.0,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,4h 45m,1 stop,No info,13302.0,1,3,2019,21,35
5,SpiceJet,Kolkata,Banglore,CCU → BLR,09:00,2h 25m,non-stop,No info,3873.0,24,6,2019,11,25
6,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,18:55,15h 30m,1 stop,In-flight meal not included,11087.0,12,3,2019,10,25
7,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,08:00,21h 5m,1 stop,No info,22270.0,1,3,2019,5,5
8,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,08:55,25h 30m,1 stop,In-flight meal not included,11087.0,12,3,2019,10,25
9,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,11:25,7h 50m,1 stop,No info,8625.0,27,5,2019,19,15

In [25]:
final_df['Dep_Time'] = final_df['Dep_Time'].str.split(' ').str[0]

In [26]:
final_df['Dep_Hour'] = final_df['Dep_Time'].str.split(':').str[0]
final_df['Dep_Min'] = final_df['Dep_Time'].str.split(':').str[1]
final_df.head(10)

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15,05,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882.0,9,6,2019,4,25,09,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1 stop,No info,6218.0,12,5,2019,23,30,18,05
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,4h 45m,1 stop,No info,13302.0,1,3,2019,21,35,16,50
5,SpiceJet,Kolkata,Banglore,CCU → BLR,09:00,2h 25m,non-stop,No info,3873.0,24,6,2019,11,25,09,00
6,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,18:55,15h 30m,1 stop,In-flight meal not included,11087.0,12,3,2019,10,25,18,55
7,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,08:00,21h 5m,1 stop,No info,22270.0,1,3,2019,5,5,08,00
8,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,08:55,25h 30m,1 stop,In-flight meal not included,11087.0,12,3,2019,10,25,08,55
9,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,11:25,7h 50m,1 stop,No info,8625.0,27,5,2019,19,15,11,25

In [ ]:
final_df['Dep_Hour'] = final_df['Dep_Hour'].astype(int)
final_df['Dep_Min'] = final_df['Dep_Min'].astype(int)

In [27]:
final_df.drop('Dep_Time', axis=1, inplace=True)

In [28]:
final_df.head(10)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15,05,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882.0,9,6,2019,4,25,09,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218.0,12,5,2019,23,30,18,05
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302.0,1,3,2019,21,35,16,50
5,SpiceJet,Kolkata,Banglore,CCU → BLR,2h 25m,non-stop,No info,3873.0,24,6,2019,11,25,09,00
6,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,15h 30m,1 stop,In-flight meal not included,11087.0,12,3,2019,10,25,18,55
7,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,21h 5m,1 stop,No info,22270.0,1,3,2019,5,5,08,00
8,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,25h 30m,1 stop,In-flight meal not included,11087.0,12,3,2019,10,25,08,55
9,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,7h 50m,1 stop,No info,8625.0,27,5,2019,19,15,11,25

In [34]:
final_df['Total_Stops'].unique()

array([nan])

In [35]:
final_df['Total_Stops'] = final_df['Total_Stops'].map({'non-stop':0, '1 stop':1, '2 stops':2, '3 stops':3, '4 stops':4, 'nan':1})
final_df.head(30)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,NaN,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,NaN,No info,7662.0,1,5,2019,13,15,05,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,NaN,No info,13882.0,9,6,2019,4,25,09,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,NaN,No info,6218.0,12,5,2019,23,30,18,05
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,NaN,No info,13302.0,1,3,2019,21,35,16,50
5,SpiceJet,Kolkata,Banglore,CCU → BLR,2h 25m,NaN,No info,3873.0,24,6,2019,11,25,09,00
6,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,15h 30m,NaN,In-flight meal not included,11087.0,12,3,2019,10,25,18,55
7,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,21h 5m,NaN,No info,22270.0,1,3,2019,5,5,08,00
8,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,25h 30m,NaN,In-flight meal not included,11087.0,12,3,2019,10,25,08,55
9,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,7h 50m,NaN,No info,8625.0,27,5,2019,19,15,11,25
10,Air India,Delhi,Cochin,DEL → BLR → COK,13h 15m,NaN,No info,8907.0,1,6,2019,23,0,09,45
11,IndiGo,Kolkata,Banglore,CCU → BLR,2h 35m,NaN,No info,4174.0,18,4,2019,22,55,20,20
12,Air India,Chennai,Kolkata,MAA → CCU,2h 15m,NaN,No info,4667.0,24,6,2019,13,55,11,40
13,Jet Airways,Kolkata,Banglore,CCU → BOM → BLR,12h 10m,NaN,In-flight meal not included,9663.0,9,5,2019,9,20,21,10
14,IndiGo,Kolkata,Banglore,CCU → BLR,2h 35m,NaN,No info,4804.0,24,4,2019,19,50,17,15
15,Air India,Delhi,Cochin,DEL → AMD → BOM → COK,26h 35m,NaN,No info,14011.0,3,3,2019,19,15,16,40
16,SpiceJet,Delhi,Cochin,DEL → PNQ → COK,4h 30m,NaN,No info,5830.0,15,4,2019,13,15,08,45
17,Jet Airways,Delhi,Cochin,DEL → BOM → COK,22h 35m,NaN,In-flight meal not included,10262.0,12,6,2019,12,35,14,00
18,Air India,Delhi,Cochin,DEL → CCU → BOM → COK,23h,NaN,No info,13381.0,12,6,2019,19,15,20,15
19,Jet Airways,Delhi,Cochin,DEL → BOM → COK,20h 35m,NaN,In-flight meal not included,12898.0,27,5,2019,12,35,16,00
20,GoAir,Delhi,Cochin,DEL → BOM → COK,5h 10m,NaN,No info,19495.0,6,3,2019,19,20,14,10
21,Air India,Banglore,New Delhi,BLR → COK → DEL,15h 20m,NaN,No info,6955.0,21,3,2019,13,20,22,00
22,IndiGo,Banglore,Delhi,BLR → DEL,2h 50m,NaN,No info,3943.0,3,4,2019,6,50,04,00
23,IndiGo,Banglore,Delhi,BLR → DEL,2h 55m,NaN,No info,4823.0,1,5,2019,21,50,18,55
24,Jet Airways,Kolkata,Banglore,CCU → BOM → BLR,13h 20m,NaN,In-flight meal not included,7757.0,6,5,2019,8,15,18,55
25,Jet Airways,Delhi,Cochin,DEL → IDR → BOM → COK,15h 10m,NaN,No info,13292.0,9,6,2019,12,35,21,25
26,IndiGo,Delhi,Cochin,DEL → LKO → COK,5h 45m,NaN,No info,8238.0,1,6,2019,3,35,21,50
27,GoAir,Delhi,Cochin,DEL → BOM → COK,5h 55m,NaN,No info,7682.0,15,5,2019,12,55,07,00
28,Vistara,Banglore,Delhi,BLR → DEL,2h 50m,NaN,No info,4668.0,18,6,2019,12,35,09,45
29,Vistara,Chennai,Kolkata,MAA → CCU,2h 15m,NaN,No info,3687.0,15,6,2019,9,20,07,05

In [36]:
final_df['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [37]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
final_df['Airline'] = label_encoder.fit_transform(final_df['Airline'])
final_df['Source'] = label_encoder.fit_transform(final_df['Source'])
final_df['Destination'] = label_encoder.fit_transform(final_df['Destination'])
final_df['Additional_Info'] = label_encoder.fit_transform(final_df['Additional_Info'])

In [39]:
final_df.shape

(13354, 15)

In [40]:
final_df.head(2)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min
0,3,0,5,BLR → DEL,2h 50m,NaN,8,3897.0,24,3,2019,1,10,22,20
1,1,3,0,CCU → IXR → BBI → BLR,7h 25m,NaN,8,7662.0,1,5,2019,13,15,05,50

In [41]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [ ]:
final_df['Airline']

In [42]:
final_df['Airline'] = ohe.fit_transform(final_df['Airline'])
final_df['Source'] = ohe.fit_transform(final_df['Source'])
final_df['Destination'] = ohe.fit_transform(final_df['Destination'])
final_df['Additional_Info'] = ohe.fit_transform(final_df['Additional_Info'])

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [44]:
pd.get_dummies(final_df, columns = ['Airline', 'Source', 'Destination', 'Additional_Info'], drop_first = True)

,Route,Duration,Total_Stops,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,...,Destination_5,Additional_Info_1,Additional_Info_2,Additional_Info_3,Additional_Info_4,Additional_Info_5,Additional_Info_6,Additional_Info_7,Additional_Info_8,Additional_Info_9
0,BLR → DEL,2h 50m,NaN,3897.0,24,3,2019,1,10,22,...,True,False,False,False,False,False,False,False,True,False
1,CCU → IXR → BBI → BLR,7h 25m,NaN,7662.0,1,5,2019,13,15,05,...,False,False,False,False,False,False,False,False,True,False
2,DEL → LKO → BOM → COK,19h,NaN,13882.0,9,6,2019,4,25,09,...,False,False,False,False,False,False,False,False,True,False
3,CCU → NAG → BLR,5h 25m,NaN,6218.0,12,5,2019,23,30,18,...,False,False,False,False,False,False,False,False,True,False
4,BLR → NAG → DEL,4h 45m,NaN,13302.0,1,3,2019,21,35,16,...,True,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13349,CCU → DEL → BLR,23h 55m,NaN,NaN,6,6,2019,20,25,20,...,False,False,False,False,False,False,False,False,True,False
13350,CCU → BLR,2h 35m,NaN,NaN,27,3,2019,16,55,14,...,False,False,False,False,False,False,False,False,True,False
13351,DEL → BOM → COK,6h 35m,NaN,NaN,6,3,2019,4,25,21,...,False,False,False,False,False,False,False,False,True,False
13352,DEL → BOM → COK,15h 15m,NaN,NaN,6,3,2019,19,15,04,...,False,False,False,False,False,False,False,False,True,False
13353,DEL → BOM → COK,14h 20m,NaN,NaN,15,6,2019,19,15,04,...,False,False,False,False,False,False,False,False,True,False